### PR TITLE
Update svgicon.md

### PR DESCRIPTION
**Pull request by Marcell-Puskas**
I have added a screenshot of all the svgs for easier selection

### CODE REVIEW

**Comment by ohitstom** [comment]
awesome work!

**Review by afonsojramos — CHANGES_REQUESTED** [review]
Can you add the image itself instead of the link?

**Comment by Marcell-Puskas** [comment]
Yes, but witch directory should I put it in?

**Comment by afonsojramos** [comment]
`static/images` should be fine 😅

**Pull request closed without merging**
